######################################################################
#                             -- prod --                              #
######################################################################
######################################################################
#                          -- spring --                              #
######################################################################
spring:
  application:
    name: ll-admin

  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ll?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password:
    hikari:
      schema: classpath:sql

  ############################ --  servlet -- ############################
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB

  ############################ --  devtools -- ############################
  devtools:
    restart:
      # 热部署开关
      enabled: true

eureka:
  client:
    enabled: true
    registry-fetch-interval-seconds: 10
    service-url:
      # default-zone 不可以（目前只能这么写）
      defaultZone:  http://127.0.0.1:8080/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

######################################################################
#                            -- log --                               #
######################################################################
logging:
  level:
    com.ll: debug
    org.springframework: warn